name: FeatureCI

on:
  push:
    branch:
      - '*'

jobs:
  RunKarateTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and run Karate tests
        run: |
          mvn clean test