name: QA Automation Manual
on:
  workflow_dispatch:
    paths:
      - 'src/test/**'
    inputs:
      env:
        description: 'env'
        type: choice
        options:
          - 'dev'
          - 'test'
          - 'stage'
          - 'herokuapp'
        required: true
        default: 'herokuapp'
      groups:
        description: 'groups'
        type: choice
        options:
          - 'smoke'
          - 'regression'
        required: true
        default: 'smoke'

jobs:
  build_and_publish:
    name: Karate Test Run On Env:${{ github.event.input.env }} Groups:${{ github.event.inputs.groups }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Karate tests
        run: |
          mvn clean test -Dtest=testRunner "-Dkarate.env=${{ github.event.inputs.env }}" '-Drp.enable=true' "-Drp.description=GitHub Actions Manual" "-Dkarate.options=--tags @${{ github.event.inputs.groups }}"

      - name: Karate Test Result report
        uses: dorny/test-report@v1
        if: success() || failure()
        with:
          name: Karate Test Results
          path: "./target/karate-reports/*.xml"
          reporter: java-junit

